#ifndef __ZEPHYR_IDL_GENERATOR_ERROR_CODE_H__
#define __ZEPHYR_IDL_GENERATOR_ERROR_CODE_H__

#define IDL_GENERATOR_ERROR_CODE_BEGIN (-100*15)

#define INCORRECT_END (-1 + IDL_GENERATOR_ERROR_CODE_BEGIN)

#define TYPE_NOT_FOUND 0

#endif`